# Generated by Django 2.2.7 on 2019-11-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaindividualizado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=400)),
                ('fecha_nacimiento', models.DateField(verbose_name='date')),
                ('parentesto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_uniforme', models.DateField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='ParteInforme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('s', 'SANTIARIA'), ('f', 'FUNCIONAL'), ('p', 'PSIQUICA'), ('so', 'SOCIAL'), ('t', 'TERAPIA OCUPACIONAL')], default='s', help_text='Tipos', max_length=2)),
                ('valoracion_inicial', models.DecimalField(decimal_places=2, max_digits=6)),
                ('objetivos', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=400)),
                ('fecha_nacimiento', models.DateField(verbose_name='date')),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
